unstable_features = true
# reorder_imports = true
# reorder_impl_items = true
group_imports = "StdExternalCrate"
# reorder_modules = true
# trailing_comma = "Never"
# use_try_shorthand = true
# format_code_in_doc_comments = true
imports_granularity = "Module"
# normalize_comments = true
# skip_children = false
